Messages:
  notEnoughArgs: '&b[&cHardcore&b] &eNo has especificado suficientes argumentos.'
  noPermission: '&b[&cHardcore&b] &eNo tienes permiso para hacer esto.'
  lifeAdded: '&b[&cHardcore&b] &eHas añadido %lifes% vida%s% a %player%.'
  lifeAddedPlayer: '&b[&cHardcore&b] &eHas ganado %lifes% vida%s%.'
  lifeAddArgs: '&b[&cHardcore&b] &eEl uso es /deathoath add <Jugador> <Vidas>'
  lifeRemoved: '&b[&cHardcore&b] &eHas quitado %lifes% vida%s% a %player%.'
  lifeRemovedPlayer: '&b[&cHardcore&b] &eHas perdido %lifes% vida%s%.'
  lifeRemoveArgs: '&b[&cHardcore&b] &eEl uso es /deathoath remove <Jugador> <Vidas>'
  lifeSet: '&b[&cHardcore&b] &eHas establecido las vidas de %player% a %lifes%.'
  lifeSetPlayer: '&b[&cHardcore&b] &eTus vidas se han establecido a %lifes%.'
  lifeSetArgs: '&b[&cHardcore&b] &eEl uso es /deathoath set <Jugador> <Vidas>'
  lifeMessage: '&b[&cHardcore&b] &eEl jugador %player% tiene %lifes% vida%s%.'
  lifeMessagePlayer: '&b[&cHardcore&b] &eTienes %lifes% vida%s%.'
  transferArgs: '&b[&cHardcore&b] &eEl uso es /deathoath transfer <Jugador> <Vidas>'
  notEnoughLifes: '&b[&cHardcore&b] &eNo tienes suficientes vidas para transferir.'
  transferMessage: '&b[&cHardcore&b] &eHas transferido %lifes% vida%s% a %player%.'
  transferPlayer: '&b[&cHardcore&b] &e%player% te ha transferido %lifes% vida%s%.'
  cannotTransferSelf: '&b[&cHardcore&b] &eNo puedes transferirte vidas a ti mismo.'
  devilPactArgs: '&b[&cHardcore&b] &eEl uso es /deathoath sacrifice/regain <Contenedores/Vidas>'
  cannotHaveLessContainers: '&b[&cHardcore&b] &eNo puedes tener menos de %containers% corazones.'
  cannotHaveMoreContainers: '&b[&cHardcore&b] &eNo puedes tener más de %containers% corazones.'
  lostContainers: '&b[&cHardcore&b] &eEl diablo ha aceptado tu trato, has perdido %containers% corazones a cambio de %lifes% vida%s%.'
  addedContainers: '&b[&cHardcore&b] &eEl diablo ha aceptado tu trato, has ganado %containers% corazones a cambio de %lifes% vida%s%.'
  youDiedTitle: '&4¡HAS MUERTO!'
  youDiedSubTitle: '&cHas perdido 1 vida'
  addedToData: '&b[&cHardcore&b] &eSe te han asignado %lifes% vidas para comenzar.'
  couldNotBeAdded: '&cHa ocurrido un error al registrar tus vidas.'
  outOfLifes: '&cHas agotado tus oportunidades, espera a que los dioses te perdonen.'
  cannotBeNegative: '&b[&cHardcore&b] &eLa cantidad de vidas no puede ser menor de 1.'
  bypass: '&b[&cHardcore&b] &eTienes la bendición de los dioses y no puedes perder vidas.'
  itemGiven: '&b[&cHardcore&b] &eHas dado una &c&lManzana de Iðunn &ea %player%.'
  itemGivenPlayer: '&b[&cHardcore&b] &eHas recibido una &c&lManzana de Iðunn&e.'
  reload: '&b[&cHardcore&b] &eSe ha recargado la configuración del plugin con éxito.'
  moneyLoss: '&b[&cHardcore&b] &eHas perdido un %percent%% de dinero al morir (%money%).'
  help:
    - "&b-===-[&cHardcore&b]-===-"
    - "&b/deathoath &eMuestra esta página."
    - "&b/deathoath get &eMuestra tus vidas."
    - "&b/deathoath get <Jugador> &eMuestra las vidas de un jugador."
    - "&b/deathoath add <Jugador> <Vidas> &eAñade vidas a un jugador."
    - "&b/deathoath remove <Jugador> <Vidas> &eResta vidas a un jugador."
    - "&b/deathoath set <Jugador> <Vidas> &eEstablece las vidas de un jugador."
    - "&b/deathoath lifeItem [Cantidad] [Jugador] &eDa una &c&lManzana de Iðunn&e."
    - "&b/deathoath transfer <Jugador> <Vidas> &eTransfiere vidas a otro jugador."
    - "&b/deathoath devilPact sacrifice <Contenedores> &eSacrifica contenedores de vida por vidas."
    - "&b/deathoath devilPact regain <Vidas> &eSacrifica vidas para ganar contenedores."
    - "&b/deathoath reload &eRecarga el plugin."
    - "&b"
    - "&eLeyenda: &b<> &eObligatorio  &b[] &eOpcional"

Config:
  initialLifes: 3
  unbanLifes: 1
  hoursOfTimeout: 24
  enableMoneyLoss: true
  moneyLossPercent: 0.2
  minContainers: -6
  maxContainers: 6

Items:
  LifeItem:
    material: ENCHANTED_GOLDEN_APPLE
    name: "&f🖤 &c&lManzana de Iðunn &f🖤"
    lore:
      - ""
      - "&7Usa esta manzana del rejuvenecimiento y la"
      - "&7inmortalidad para añadir %lifes% vida%s% a tu contador."
    baseItemAmount: 1