name: DeathOath
version: 1.1
main: wbe.deathoath.DeathOath
api-version: 1.21
depend: [Vault]
softdepend: [ProtocolLib, PlaceholderAPI]
author: wbe
commands:
  DeathOath:
    description: DeathOath main command
    aliases: [deatho, doath, doth]
    permission: deathoath.command
