Variables:
  initialLifes: 3
  unbanLifes: 1
  hoursOfTimeout: 24
Messages:
  notEnoughArgs: '&b[&cHardcore&b] &eNo has especificado suficientes argumentos.'
  noPermission: '&b[&cHardcore&b] &eNo tienes permiso para hacer esto.'
  lifeAdded: '&b[&cHardcore&b] &eHas añadido %lifes% vida%s% a %player%.'
  lifeAddedPlayer: '&b[&cHardcore&b] &eHas ganado %lifes% vida%s%.'
  lifeRemoved: '&b[&cHardcore&b] &eHas quitado %lifes% vida%s% a %player%.'
  lifeRemovedPlayer: '&b[&cHardcore&b] &eHas perdido %lifes% vida%s%.'
  lifeSet: '&b[&cHardcore&b] &eHas establecido las vidas de %player% a %lifes%.'
  lifeSetPlayer: '&b[&cHardcore&b] &eTus vidas se han establecido a %lifes%.'
  lifeMessage: '&b[&cHardcore&b] &eEl jugador %player% tiene %lifes% vida%s%.'
  lifeMessagePlayer: '&b[&cHardcore&b] &eTienes %lifes% vida%s%.'
  youDiedTitle: '&4¡HAS MUERTO!'
  youDiedSubTitle: '&cHas perdido 1 vida'
  addedToData: '&b[&cHardcore&b] &eSe te han asignado %lifes% vidas para comenzar.'
  couldNotBeAdded: '&cHa ocurrido un error al registrar tus vidas.'
  outOfLifes: '&cHas agotado tus oportunidades, espera a que los dioses te perdonen.'
  cannotBeNegative: '&b[&cHardcore&b] &eLa cantidad de vidas no puede ser menor de 1.'
  bypass: '&b[&cHardcore&b] &eTienes la bendición de los dioses y no puedes perder vidas.'
  help:
    - "&b-===-[&cHardcore&b]-===-"
    - "&b/deathoath &eMuestra esta página."
    - "&b/deathoath get &eMuestra tus vidas."
    - "&b/deathoath get <Jugador> &eMuestra las vidas de un jugador."
    - "&b/deathoath add <Jugador> <Vidas> &eAñade vidas a un jugador."
    - "&b/deathoath remove <Jugador> <Vidas> &eResta vidas a un jugador."
    - "&b/deathoath set <Jugador> <Vidas> &eEstablece las vidas de un jugador."